services:
 
  ghost:
    build: .
    ports:
      - 8080:2368
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: V4A3Msq#M3Xdv#Cf
      database__connection__database: ghost
    entrypoint: ["wait-for-it.sh", "db:3306", "--timeout=300", "--", "docker-entrypoint.sh"]
    command: ["node", "current/index.js"]
    volumes:
      - "ghost:/bitnami/ghost"
    networks:
      - public
      - private
    depends_on:
      - db
    deploy:
      replicas: 1
 
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: V4A3Msq#M3Xdv#Cf
    volumes:
      - "db:/var/lib/mysql"
    networks:
      - private
    deploy:
      replicas: 1
 
volumes:
  ghost:
  db:
 
networks:
  public:
  private: